// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProviderOptimizer.Persistence;

#nullable disable

namespace OptimizerProvider.Infrastructure.Migrations
{
    [DbContext(typeof(ProviderOptimizerDbContext))]
    partial class ProviderOptimizerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("optimizer")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.OptimizationRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ClientLatitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("ClientLongitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestId");

                    b.ToTable("optimization_requests", "optimizer");
                });

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.OptimizationResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("EtaMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ResultId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RequestId");

                    b.ToTable("optimization_results", "optimizer");
                });

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(5.00m);

                    b.Property<string>("ServiceTypes")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("ProviderId");

                    b.ToTable("providers", "optimizer");
                });

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.ProviderAvailability", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ProviderId");

                    b.ToTable("provider_availability", "optimizer");
                });

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.ProviderLocation", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ProviderId");

                    b.ToTable("provider_location", "optimizer");
                });

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.ProviderWorkload", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveCases")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ProviderId");

                    b.ToTable("provider_workload", "optimizer");
                });

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.OptimizationResult", b =>
                {
                    b.HasOne("ProviderOptimizer.Domain.Entities.Provider", "Provider")
                        .WithMany("OptimizationResults")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProviderOptimizer.Domain.Entities.OptimizationRequest", "Request")
                        .WithMany("Results")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.ProviderAvailability", b =>
                {
                    b.HasOne("ProviderOptimizer.Domain.Entities.Provider", "Provider")
                        .WithOne("Availability")
                        .HasForeignKey("ProviderOptimizer.Domain.Entities.ProviderAvailability", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.ProviderLocation", b =>
                {
                    b.HasOne("ProviderOptimizer.Domain.Entities.Provider", "Provider")
                        .WithOne("Location")
                        .HasForeignKey("ProviderOptimizer.Domain.Entities.ProviderLocation", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.ProviderWorkload", b =>
                {
                    b.HasOne("ProviderOptimizer.Domain.Entities.Provider", "Provider")
                        .WithOne("Workload")
                        .HasForeignKey("ProviderOptimizer.Domain.Entities.ProviderWorkload", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.OptimizationRequest", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("ProviderOptimizer.Domain.Entities.Provider", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("Location");

                    b.Navigation("OptimizationResults");

                    b.Navigation("Workload");
                });
#pragma warning restore 612, 618
        }
    }
}
